name: val
favicon: null
layout_spectrum: 0.40221401513554156
typography_spectrum: 0.5762308244593441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.337281089508906
  lightness: 0.28310646233148873
  saturation: 0.11298644682392478
  rhythmicContrast: 0.490739852655679
purpose: []
